var app=new Vue({
    el:'#app',
    data:{
        columns:[
            {
                title:'姓名',
                key:'name'

            },
            {
                title:'年龄',
                key:'age',
                sortable:true
            },
            {
                title:'出生日期',
                key:'age',
                sortable:true
            },
            {
                title:'地址',
                key:'address'
            }
        ],
        data:[
            {
                name:'王小明',
                age:18,
                birthday:'1999-02-21',
                address:'北京市朝阳区芍药居'
            },
            {
                name:'张晓刚',
                age:18,
                birthday:'1999-02-21',
                address:'北京市朝阳区芍药居'
            },{
                name:'周小伟',
                age:19,
                birthday:'1999-02-21',
                address:'北京市朝阳区芍药居'
            },{
                name:'李晓红',
                age:20,
                birthday:'1999-02-21',
                address:'北京市朝阳区芍药居'
            }
        ]
    },
    methods:{
        handleAddData:function(){
            this.data.push({
                name:'刘晓彤',
                age:22,
                birthday:'1998-05-30',
                address:'北京市东城区东直门'
            })
        }
    }

})